# Generated by Django 5.1.7 on 2025-03-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagement', '0002_alter_registration_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('clothing', 'Clothing'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('housing', 'Housing'), ('education', 'Education'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('gift', 'Gift'), ('rental', 'Rental'), ('bonus', 'Bonus'), ('other', 'Other')], max_length=50),
        ),
    ]
