# Generated by Django 5.1.7 on 2025-03-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagement', '0005_alter_expense_category_alter_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('clothing', 'Clothing'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('housing', 'Housing'), ('loans', 'Loans'), ('beauty', 'Beauty'), ('gifts', 'Gifts'), ('education', 'Education'), ('other', 'Other')], max_length=50),
        ),
    ]
